### ISSUE TITLE
Question about the additional initialization step on DyNeRF dataset in 4.2

### ISSUE THREAD

**Issue by SJoJoK** [fudan-zvg/4d-gaussian-splatting#1]
Hello, Thanks for you great work!
I'm handling the DyNeRF dataset with 3D Gaussian Splatting, too. I found that in scenes like `flames salmon`, the distant background is messy since COLMAP cant reconstruct it successfully. The Sec 4.2 of the paper describe a solution of it ,which is

> For scenes in the Plenoptic Video dataset, we introduced an additional initialization step. We initialized the Gaussian with 100,000 extra points distributed uniformly on the sphere encompassing the entire scene. This step aimed to accommodate the distant background, which was not successfully reconstructed by colmap. We then terminated the optimization process after 10,000 iterations.

Can you please elaborate on it? Does the "entire scene" include the distant buildings and trees? Or it just includes the room? Besides, does the points distributed within the sphere, or on the spherical surface?

Thanks in advance for any help or advice.

**Comment by Alexander0Yang** [comment]
Hi, @SJoJoK. Thanks for your interest.

This solution draws inspiration from the taichi implementation of 3d gaussian splatting, you can refer to [taichi_3d_gaussian_splatting/taichi_3d_gaussian_splatting/GaussianPointCloudScene.py at main · wanmeihuali/taichi_3d_gaussian_splatting (github.com)](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/blob/main/taichi_3d_gaussian_splatting/GaussianPointCloudScene.py#L178). The range of the "entire scene" is very empirical, and for the `flame salmon`, we set the radius of the sphere to be 60m.

BTW, I find that a more straightforward solution is to optimize a learnable grid on the spherical surface as the background model, which is easier to optimize and can produce better results.

Hope that would help.

**Comment by SJoJoK** [comment]
Thank you @Alexander0Yang , your information is very helpful, and I'll give it a try. I apologize for the additional question, but I wanted to clarify something in the paper. When it states, 'We then terminated the optimization process after 10,000 iterations,' does this mean you trained the Gaussians for 10,000 iterations and halted densification at iteration 5,000, or established the initial Gaussians after 10,000 iterations of optimization, followed by a training process of 30,000 iterations?

**Comment by Alexander0Yang** [comment]
Sorry for the confusion! 
We only terminate the optimization of the background model at the 10,000-th iterations. This is because we observed that there is an inconsistency in the optimization pace of the foreground and background. The background model could already working well by the 10,000-th iterations, and further optimization would result in the spherical initialized points are “leaked” and thus lose their function as a background. A similar situation also holds for the learnable grid; while it itself does not leak, it can cause the foreground leak and thus lead to overfitting.

**Comment by SJoJoK** [comment]
Got it,thanks for the information:) I'll close this issue.
