### ISSUE TITLE
How to Visualize or test the training results？

### ISSUE THREAD

**Issue by ch1998** [fudan-zvg/4d-gaussian-splatting#12]
According to the guidelines you gave, I completed the data training. The psnr results during the training process were very high, but how to visualize or render the results?

**Comment by Alexander0Yang** [comment]
Hi @ch1998 
The current code evaluates quantitative metrics on all test views and visualizes some of them in tensorboard during training. 
Since the checkpoint already captures all parameters of the 4D Gaussians, I believe that by applying slight adaption to the original 3DGS's render.py, it can be employed to visualize the training result within our framework.

**Comment by ookey** [comment]
Hi there,
I just made a quick render.py adaptation for the same purpose. In case it helps I join the git patch.
I launched it with:
```
$ python render.py --model_path output/dnerf/lego/ --loaded_pth=output/dnerf/lego/chkpnt_best.pth
```
[render_patch.txt](https://github.com/fudan-zvg/4d-gaussian-splatting/files/14182511/render_patch.txt)

Regards,
Matthieu.

**Comment by cmh1027** [comment]
@ookey could you share the code please?

**Comment by ookey** [comment]
Hi @cmh1027 
You just have to:
1. download the `render_patch.txt` file (see post above) at the root of the project (in 4d-gaussian-splatting folder)
2. execute the command `git apply render_patch.txt`

This should add a file called render.py + change (slightly) `scene/__init__.py`

@Alexander0Yang tell me if you want me to issue a PR.

**Comment by darthandvader** [comment]
Hi, I encountered "command not found" after following your instruction, my command is "python3 render.py --model_path output/dnerf/hellwarrior/ --loaded_pth=output/dnerf//hellwarrior/chkpnt30000.th"

**Comment by darthandvader** [comment]
hi, I followed your instruction, but when I tried "python3 render.py --model_path output/dnerf/hellwarrior/ --loaded_pth=output/dnerf/hellwarrior/chkpnt30000.pth", it still showed command not found

**Comment by ookey** [comment]
"command not found"? This is probably because python3 is not known in your shell. Try `python render.py --model_path output/dnerf/hellwarrior/ --loaded_pth=output/dnerf/hellwarrior/chkpnt30000.pth` :-)

**Comment by RNGrunshen** [comment]
> hi, I followed your instruction, but when I tried "python3 render.py --model_path output/dnerf/hellwarrior/ --loaded_pth=output/dnerf/hellwarrior/chkpnt30000.pth", it still showed command not found

please try the following command, we should  add " "  to str path

python render.py --model_path "output/dnerf/standup/" --loaded_pth="output/dnerf/standup/chkpnt_best.pth"

**Comment by cdfan0627** [comment]
> Hi @cmh1027 You just have to:
> 
> 1. download the `render_patch.txt` file (see post above) at the root of the project (in 4d-gaussian-splatting folder)
> 2. execute the command `git apply render_patch.txt`
> 
> This should add a file called render.py + change (slightly) `scene/__init__.py`
> 
> @Alexander0Yang tell me if you want me to issue a PR.



> Hi there, I just made a quick render.py adaptation for the same purpose. In case it helps I join the git patch. I launched it with:
> 
> ```
> $ python render.py --model_path output/dnerf/lego/ --loaded_pth=output/dnerf/lego/chkpnt_best.pth
> ```
> 
> [render_patch.txt](https://github.com/fudan-zvg/4d-gaussian-splatting/files/14182511/render_patch.txt)
> 
> Regards, Matthieu.

Hi 
It only visualize training data result.
Can I visualize testing data result?

**Comment by ookey** [comment]
hello @cmh1027 ,
I'm sorry I don't have a mean to test it on this computer. Reviewing quickly the code seems to show a "test" subdirectory should be created with the test output images, if scene has a `test_cameras` list. You will have to dig into the code by yourself :-/
Matthieu.

**Comment by caiobarrosv** [comment]
> Hi there, I just made a quick render.py adaptation for the same purpose. In case it helps I join the git patch. I launched it with:
> 
> ```
> $ python render.py --model_path output/dnerf/lego/ --loaded_pth=output/dnerf/lego/chkpnt_best.pth
> ```
> 
> [render_patch.txt](https://github.com/fudan-zvg/4d-gaussian-splatting/files/14182511/render_patch.txt)
> 
> Regards, Matthieu.

@ookey, the render.txt file seems to be incomplete.

How can I visualize the training results?

**Comment by Zain-Razzaq** [comment]
@ookey your script gives output in form of pictures. Cant we get the result in video form as shown in the result of github repo by author

**Comment by ookey** [comment]
> @ookey your script gives output in form of pictures. Cant we get the result in video form as shown in the result of github repo by author

Hello @Zain-Razzaq ,
I'm sorry I no longer have the software installed. I guess that as simple ffmpeg command would produce a video from the images.  see https://ffmpeg.org/

**Comment by GuoPingPan** [comment]
@ookey  Hi, bro. Thank you for providing the rendering solution. Why is the rendering on RTX4090 only about 2fps?
![image](https://github.com/user-attachments/assets/bcafcdf9-5dfb-441c-ba4f-f95fc0ced71e)

**Comment by hhxphh** [comment]
> @ookey Hi, bro. Thank you for providing the rendering solution. Why is the rendering on RTX4090 only about 2fps? ![image](https://private-user-images.githubusercontent.com/69315544/363456330-bcafcdf9-5dfb-441c-ba4f-f95fc0ced71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTM2MjQsIm5iZiI6MTczNjQ5MzMyNCwicGF0aCI6Ii82OTMxNTU0NC8zNjM0NTYzMzAtYmNhZmNkZjktNWRmYi00NDFjLWJhNGYtZjk1ZmMwY2VkNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDA3MTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMGYxZDQ1MmFhZTg2ODFiYTNmMzdjMTNlYjI5MjNjOTlhMjM3YWM0NjRmOTJmYzkyYjk2MmMxMzRkYzJlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Vmk9GMtEI2e46N7Hmtu6L_Pl2U7c1dIttOy7Wn8snQ)

me too. Do you solve this problem now?
