### ISSUE TITLE
Is there any plan to support Nerfies (HyperNeRF) dataset?

### ISSUE THREAD

**Issue by cmh1027** [fudan-zvg/4d-gaussian-splatting#13]
I see that only dnerf and dynerf datasets are supported. Is there any plan to add support for hypernerf dataset?

**Comment by Alexander0Yang** [comment]
Supporting more datasets is not in our short-term (maybe just several days) release plan.
However, it is not difficult to slightly modify the dataset reader to run our code on a HyperNeRF dataset by referring to some concurrent works such as [Deformable 3DGS](https://github.com/ingra14m/Deformable-3D-Gaussians) and [4DGaussian](https://github.com/hustvl/4DGaussians).
