### ISSUE TITLE
Cannot calculate optical flow on Plenoptic Video dataset due to large image size

### ISSUE THREAD

**Issue by Zerg-Overmind** [fudan-zvg/4d-gaussian-splatting#19]
Hi, thanks for the great work.
I was trying to calculate optical flow on Plenoptic Video dataset by using videoflow (mentioned in the paper) but failed due to the large image size. Did you calculate the optical flow on original resolution of the dataset or do it after downsampling?
Thanks.

I just found that your downsampling rate is 1/2. Then I don't have any other question :)

**Comment by GANWANSHUI** [comment]
Hi @Zerg-Overmind , may I ask how to generate the render flow as illustrated in Fig 4? Thank you!

**Comment by Zerg-Overmind** [comment]
Hi @GANWANSHUI , just downsampling the GT images/rendered images into their 1/2 and then following videoflow mentioned in the paper.

**Comment by GANWANSHUI** [comment]
Hi @Zerg-Overmind . Thanks a lot for the quick reply. I mean the rendered flow.

I tried to train the 4dgs under the synthesis scene (dnerf), but the output [flow value](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/896189e0363ec691a23cb6ddbd67372353c73d1c/gaussian_renderer/__init__.py#L191) is zero how to enable the optical flow function? Or did I miss anything?

thanks again!

**Comment by Zerg-Overmind** [comment]
Hi @GANWANSHUI , I don't think they've enabled this function. Flow values are [initialized](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/main/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L528) as 0 and then updated by [this](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/main/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L583), which should always 0 after multiplication. Let me know if I am wrong cuz I didn't go through the details..

**Comment by GANWANSHUI** [comment]
Hi @Zerg-Overmind , Thanks a lot for the hint. I think so and the function may need to wait for the author's update.
