### ISSUE TITLE
Fail to reproduce performance in some scenes

### ISSUE THREAD

**Issue by bbangsik13** [fudan-zvg/4d-gaussian-splatting#24]
Congratulations on your acceptance of the paper!

I experimented with N3V dataset through the code you provided, but I can't reproduce the performance in certain scenes. Can I get some advice?

I tested with the environment you provided and COLMAP 3.9 & 3.10 version.

![image](https://github.com/fudan-zvg/4d-gaussian-splatting/assets/78462588/bdc5e461-cf41-4ddd-939c-1e0fbb89ab45)

https://github.com/fudan-zvg/4d-gaussian-splatting/assets/78462588/e43e93ad-9f29-485a-ba07-d868b3b1e543

https://github.com/fudan-zvg/4d-gaussian-splatting/assets/78462588/ec0dd32f-f92f-48ed-bec6-806bcb27655c

**Comment by Alexander0Yang** [comment]
Have you made any modifications to the config? It looks like the bgmap didn’t work.

It seems that the view outside the window was completely occluded by the Gaussians distributed on the window, and there are some undesired accumulations opacity causing black shadows on the walls.

This might be because some Gaussians are less constrained in some training view. This could be related to initialization, but I have never encountered this situation. 😂
BTW, my colmap version is also 3.9.

Perhaps providing some intermediate results from the training would be more informative for identifying the problem.

If the issue is still not resolved, I would provide you with a checkpoint file in the next few days to help your reproduction.

**Comment by bbangsik13** [comment]
Thank you for your quick reply. 

I checked the point cloud input and intermediate rendering results and found no problem. 

<img width="454" alt="image" src="https://github.com/fudan-zvg/4d-gaussian-splatting/assets/78462588/085ec8ca-187d-440d-b828-0038152d03e9">

<img width="515" alt="image" src="https://github.com/fudan-zvg/4d-gaussian-splatting/assets/78462588/4ecb4644-31cc-4b1f-b39a-6030225e0a09">


https://github.com/fudan-zvg/4d-gaussian-splatting/assets/78462588/85ba2571-9184-4593-9f1f-53443c35ce91



Additionally, the specific values of the config for the failed scenes (Martini & Salmon) and the well-reconstructed scenes (other scenes) are different, so I wonder if you meant it.
PipelineParams.env_map_res and PipelineParams.env_optimize_until have different values (see below) 
[[config/dynerf/coffee_martini.yaml](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/896189e0363ec691a23cb6ddbd67372353c73d1c/configs/dynerf/coffee_martini.yaml#L29)] vs [[config/dynerf/cook_spinach.yaml](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/896189e0363ec691a23cb6ddbd67372353c73d1c/configs/dynerf/cook_spinach.yaml#L29)]

BTW, I didn't modify the config file you provided. 😂

**Comment by Alexander0Yang** [comment]
Hi bbangsik13,
[Here] (https://drive.google.com/drive/folders/1bVMRVvg-saNqqY6Boc6Na5q8oWZvtZh3?usp=sharing) is my checkpoint, tensorboard record, and input point cloud generated during testing the open-sourced code. 

I just verified the released code in a different environment and was still able to reproduce the similar result.

> I checked the point cloud input and the intermediate rendering results and found no problem.

I mean the quantitative results recorded in tensorboard during training. Checking how these metrics changed might be helpful. As can be seen in our tensorboard, the psnr have not been so bad even in the 500 iterations.

It is very weird. Could you provide more detailed environment information for locating the problem?

**Comment by Alexander0Yang** [comment]
Hi @bbangsik13,
[Here](https://drive.google.com/drive/folders/1bVMRVvg-saNqqY6Boc6Na5q8oWZvtZh3?usp=sharing) is my checkpoint, tensorboard record, and input point cloud generated during testing the open-sourced code. 

I just verified the released code in a different environment and was still able to reproduce the similar result.

> I checked the point cloud input and the intermediate rendering results and found no problem.

I mean the quantitative results recorded in tensorboard during training. Checking how these metrics changed might be helpful. As can be seen in our tensorboard, the psnr have not been so bad even in the 500 iterations.

It is very weird. Could you provide more detailed environment information for locating the problem?

**Comment by bbangsik13** [comment]
I think I've solved the problem.

I used the render code of [#12](https://github.com/fudan-zvg/4d-gaussian-splatting/issues/12) to measure the metric after rendering. When I debugged the ```render.py``` , there was a problem that the parameter ```env_map``` of the ckpt did not loaded. Changing the code to load it up, the result came out close to the result of the tensorboard you shared.

Only salmon and martini scenes use env_map, so I think the results came out right in other scenes.

Thank you for your assistance.

**Comment by Joaquin-Gajardo** [comment]
@bbangsik13 could you share your code to evaluate the metrics? and what was your specific change for loading up the `env_map` parameter correctly?

Thanks!

> I think I've solved the problem.
> 
> I used the render code of [#12](https://github.com/fudan-zvg/4d-gaussian-splatting/issues/12) to measure the metric after rendering. When I debugged the `render.py` , there was a problem that the parameter `env_map` of the ckpt did not loaded. Changing the code to load it up, the result came out close to the result of the tensorboard you shared.
> 
> Only salmon and martini scenes use env_map, so I think the results came out right in other scenes.
> 
> Thank you for your assistance.

**Comment by bbangsik13** [comment]
Hi @Joaquin-Gajardo, sorry for the late response.
 
As it's been a while since I made those modifications, I'm not sure about all details.

For the code from [#12](https://github.com/fudan-zvg/4d-gaussian-splatting/issues/12), It does not load envmap options from the yaml file and values from the checkpoint. 
While I'm not entirely certain, maybe I hardcoded the envmap options and modified scene.\_\_init\_\_.py line 81 to use the restore function instead of create_from_pth. I could have organized the code better but preferred not to at the time. The only requirement is to load the trained env_map.

If you're still experiencing issues, please feel free to contact me via email and I'll be happy to help.
