### ISSUE TITLE
license

### ISSUE THREAD

**Issue by robinsonkwame** [fudan-zvg/4d-gaussian-splatting#5]
Love this work! I assume the repo is licensed MIT/Apache. (edited)

**Comment by robinsonkwame** [comment]
Ah, this project was forked from the 3D Gaussian splatting, not just inspired by it, and so this code is all non-commercial use only.

**Comment by Alexander0Yang** [comment]
Hi @robinsonkwame. 
Thanks for the suggestion. This project is crafted for research purposes only. We have added a MIT LICENSE for this work and included license of 3D Gaussian splatting in [LICENSE_gaussian_splatting.md](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/main/LICENSE_gaussian_splatting.md). to which this work also subjects.
