### ISSUE TITLE
Some prolems with feature_rest when training

### ISSUE THREAD

**Issue by tingzhongyue** [fudan-zvg/4d-gaussian-splatting#50]
Thank you for your great work and contribution.

When I tried to train 4dgs, I found that although ` active_sh_degree_t = 2`, `sh[16:]` which should calculate 4D spherindrical harmonics was still 0.

I trained it on `sear_steak` dataset, and no hyperparameters were modified.

Do you ever meet some problems like this, and do you know any method to solve it?

**Comment by Alexander0Yang** [comment]
Hi @tingzhongyue!
Thank you for pointing this out. You can turn on `convert_SHs_python` to reproduce the experiments in our paper. There are still some legacy bugs in the current CUDA version, although they don't significantly affect performance. 
I will fix them as soon as possible.

**Comment by Alexander0Yang** [comment]
Hi @tingzhongyue!
Thank you for pointing this out. You can turn on `convert_SHs_python` to reproduce the experiments in our paper. Now the CUDA version does not exactly match the behavior of the python version, although they don't significantly affect performance. 
I will fix them as soon as possible.
